name: Daily Email Digest

on:
  schedule:
    # Run at 9 AM UTC every day (4 AM EST / 1 AM PST)
    - cron: '0 9 * * *'
  
  # Allow manual trigger for testing
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Send test email instead of daily digest'
        required: false
        type: boolean
        default: false

env:
  NODE_ENV: production

jobs:
  send-daily-digest:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd github-actions-backend
          npm install --omit=dev
      
      - name: Check email configuration
        run: |
          echo "📧 Checking email configuration..."
          echo "SMTP_HOST: ${{ secrets.SMTP_HOST && '✓ Configured' || '✗ Missing' }}"
          echo "SMTP_USER: ${{ secrets.SMTP_USER && '✓ Configured' || '✗ Missing' }}"
          echo "SMTP_PASS: ${{ secrets.SMTP_PASS && '✓ Configured' || '✗ Missing' }}"
          
          if [ -z "${{ secrets.SMTP_HOST }}" ] || [ -z "${{ secrets.SMTP_USER }}" ] || [ -z "${{ secrets.SMTP_PASS }}" ]; then
            echo ""
            echo "⚠️  Email not configured! Please add these secrets:"
            echo "  - SMTP_HOST (e.g., smtp.gmail.com)"
            echo "  - SMTP_PORT (e.g., 587)"
            echo "  - SMTP_USER (your email address)"
            echo "  - SMTP_PASS (app password for Gmail)"
            echo "  - NOTIFICATION_EMAIL (optional recipient)"
            echo ""
            echo "Go to: Settings → Secrets and variables → Actions"
            exit 1
          fi
      
      - name: Send test email
        if: ${{ inputs.test_mode }}
        run: |
          cd github-actions-backend
          echo "📧 Sending test email..."
          node email-notifications-enhanced.js test
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
      
      - name: Send daily digest email
        if: ${{ !inputs.test_mode }}
        run: |
          cd github-actions-backend
          echo "📧 Sending daily digest email..."
          node email-notifications-enhanced.js daily
          
          echo ""
          echo "✅ Daily digest sent successfully!"
          echo "Next scheduled run: Tomorrow at 9 AM UTC"
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
      
      - name: Export email summary
        if: always()
        run: |
          cd github-actions-backend
          echo "📊 Exporting email summary for dashboard..."
          node email-notifications-enhanced.js export
