name: Fix PostgreSQL Analysis Schema

on:
  workflow_dispatch:

jobs:
  fix-analysis-schema:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: |
        cd github-actions-backend
        npm install
    
    - name: Run analysis schema fix
      env:
        POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
      run: |
        cd github-actions-backend
        node fix-postgres-analysis-schema.js
