name: System Health Check

on:
  # Run every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  health-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd github-actions-backend
          npm install --omit=dev
      
      - name: Run health check
        run: |
          cd github-actions-backend
          node health-check.js
      
      - name: Create issue if unhealthy
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.HEALTH_MONITORING_SECRETS }}
          script: |
            const title = `🚨 System Health Check Failed`;
            const body = `The automated health check detected issues with the AI Monitor system.
            
            Please investigate the logs for details.
            
            Workflow run: ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
            
            ---
            *Automated health check alert*`;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['bug', 'health-check', 'automated']
            });
