name: Quick PostgreSQL Company Cleanup

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cleanup-companies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd github-actions-backend
          npm install pg
      
      - name: Run PostgreSQL cleanup
        run: |
          cd github-actions-backend
          node quick-postgres-company-cleanup.js
        env:
          POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
      
      - name: Summary
        run: |
          echo "✅ PostgreSQL companies have been reduced to 6 companies only!"