name: Test Email Configuration

on:
  # Manual trigger only
  workflow_dispatch:
    inputs:
      email_type:
        description: 'Type of test email to send'
        required: true
        default: 'test'
        type: choice
        options:
          - test
          - daily
          - state
          - check

env:
  NODE_ENV: production

jobs:
  test-email:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd github-actions-backend
          npm install --omit=dev
      
      - name: Test Email Configuration
        run: |
          cd github-actions-backend
          
          echo "📧 Testing Email Configuration"
          echo "=============================="
          echo ""
          
          # Check configuration
          if [ -z "$SMTP_HOST" ]; then
            echo "❌ ERROR: Email not configured!"
            echo ""
            echo "To enable email notifications, you MUST add these secrets:"
            echo ""
            echo "1. Go to: https://github.com/redmorestudio/ai-competitive-monitor/settings/secrets/actions"
            echo ""
            echo "2. Add these secrets:"
            echo "   - SMTP_HOST=smtp.gmail.com"
            echo "   - SMTP_PORT=587"
            echo "   - SMTP_USER=your-email@gmail.com"
            echo "   - SMTP_PASS=your-app-password (NOT your regular password!)"
            echo "   - NOTIFICATION_EMAIL=seth@redmore.studio (or your email)"
            echo ""
            echo "3. For Gmail, get an app password at:"
            echo "   https://myaccount.google.com/apppasswords"
            echo ""
            exit 1
          fi
          
          echo "✅ Email Configuration Found!"
          echo ""
          echo "Settings:"
          echo "- SMTP Host: $SMTP_HOST"
          echo "- SMTP Port: ${SMTP_PORT:-587}"
          echo "- SMTP User: $SMTP_USER"
          echo "- Recipient: ${NOTIFICATION_EMAIL:-$SMTP_USER}"
          echo "- Email Type: ${{ inputs.email_type }}"
          echo ""
          
          # Send test email based on type
          case "${{ inputs.email_type }}" in
            "test")
              echo "📨 Sending test email..."
              node email-notifications-enhanced.js test || exit 1
              ;;
            
            "daily")
              echo "📨 Sending daily digest email..."
              node email-notifications-enhanced.js daily
              ;;
            
            "state")
              echo "📨 Sending complete state report email..."
              node email-notifications-enhanced.js state
              ;;
            
            "check")
              echo "📨 Checking for alerts to send..."
              node email-notifications-enhanced.js check
              ;;
          esac
          
          if [ $? -eq 0 ]; then
            echo ""
            echo "✅ Email test completed! Check your inbox."
          else
            echo ""
            echo "❌ Email test failed! Check the error messages above."
            exit 1
          fi
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_SECURE: ${{ secrets.SMTP_SECURE }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
