name: Test Email Configuration

on:
  # Allow manual trigger only
  workflow_dispatch:

env:
  NODE_ENV: production

jobs:
  send-test-email:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd github-actions-backend
          npm install --omit=dev
      
      - name: Check email configuration
        run: |
          echo "📧 Checking email configuration..."
          echo "SMTP_HOST: ${{ secrets.SMTP_HOST && '✓ Configured' || '✗ Missing' }}"
          echo "SMTP_USER: ${{ secrets.SMTP_USER && '✓ Configured' || '✗ Missing' }}"
          echo "SMTP_PASS: ${{ secrets.SMTP_PASS && '✓ Configured' || '✗ Missing' }}"
          echo "SMTP_PORT: ${{ secrets.SMTP_PORT && '✓ Configured' || '✗ Missing' }}"
          echo "NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL && '✓ Configured' || '(using default)' }}"
          
          if [ -z "${{ secrets.SMTP_HOST }}" ] || [ -z "${{ secrets.SMTP_USER }}" ] || [ -z "${{ secrets.SMTP_PASS }}" ]; then
            echo ""
            echo "⚠️  Email not configured! Please add these secrets:"
            echo "  - SMTP_HOST (e.g., smtp.gmail.com)"
            echo "  - SMTP_PORT (e.g., 587)"
            echo "  - SMTP_USER (your email address)"
            echo "  - SMTP_PASS (app password for Gmail)"
            echo "  - NOTIFICATION_EMAIL (optional recipient)"
            echo ""
            echo "Go to: Settings → Secrets and variables → Actions"
            exit 1
          fi
      
      - name: Send test email
        run: |
          cd github-actions-backend
          echo "📧 Sending test email..."
          node email-notifications-enhanced.js test
          
          echo ""
          echo "✅ Test email sent successfully!"
          echo "Check your inbox to verify email delivery."
          echo ""
          echo "Email sent to: ${NOTIFICATION_EMAIL:-seth@redmore.studio}"
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USER: ${{ secrets.SMTP_USER }}
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
