name: Update PostgreSQL Companies from JSON

on:
  workflow_dispatch:
  push:
    paths:
      - 'api-data/companies.json'

permissions:
  contents: read

jobs:
  update-postgres:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: |
          cd github-actions-backend
          npm install --omit=dev
      
      - name: Update PostgreSQL companies
        run: |
          cd github-actions-backend
          node update-postgres-companies-from-json.js
        env:
          POSTGRES_CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
      
      - name: Summary
        run: |
          echo "✅ PostgreSQL companies table has been updated to match companies.json"